# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openbao
  namespace: flux-system
spec:
  targetNamespace: openbao
  interval: 10m0s
  prune: true
  wait: true
  path: ./kubernetes/core/salamandre/base/openbao/app
  sourceRef:
    kind: GitRepository
    name: flux-system
