argument_specs:
  main:
    short_description: The main entry point for the OpenBao secret.
    options:
      updatable:
        type: bool
        default: true
      path:
        type: str
        required: true
      data:
        type: dict
        required: true
