apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: openbao-eso
spec:
  provider:
    vault:
      server: http://openbao-internal.openbao.svc:8200
      auth:
        kubernetes:
          mountPath: kubernetes
          role: external-secrets
          serviceAccountRef:
            name: openbao-auth
            namespace: external-secrets
  retrySettings:
    maxRetries: 30
    retryInterval: 10s
