apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: openbao-eso
spec:
  provider:
    vault:
      server: https://secrets.${DOMAIN_NAME}
      auth:
        kubernetes:
          mountPath: baku-cluster
          role: external-secrets
          serviceAccountRef:
            name: openbao-auth
            namespace: external-secrets
  retrySettings:
    maxRetries: 30
    retryInterval: 10s
