apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: baku-s3
spec:
  retentionPolicy: "30d"
  configuration:
    destinationPath: s3://backup-salamandre-pg/
    endpointURL: https://baku.${DOMAIN_NAME}:3882
    s3Credentials:
      accessKeyId:
        name: cnpg-s3-credentials
        key: S3_ACCESS_KEY
      secretAccessKey:
        name: cnpg-s3-credentials
        key: S3_SECRET_KEY
    data:
      compression: bzip2
    wal:
      compression: bzip2
  instanceSidecarConfiguration:
    resources:
      requests:
        cpu: 5m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 2.5Gi
