# vscode-kubernetes-tools: exclude
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/monitoring
  - ../base/nextcloud
  - ../base/vaultwarden
  - ../base/forgejo
  - ../base/backup
