apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: secrets-${DOMAIN_NAME/./-}
spec:
  endpoints:
    - dnsName: secrets.${DOMAIN_NAME}
      recordType: CNAME
      targets:
        - ${ROOT_DOMAIN_NAME}
