apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cronjob.yaml
  - pvc.yaml
  - rbac.yaml
  - secret.yaml
configMapGenerator:
  - name: backup-script
    options:
      labels:
        kustomize.toolkit.fluxcd.io/substitute: disabled
    files:
      - backup.sh
