# vscode-kubernetes-tools: exclude
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/seaweedfs
patches:
  - patch: |-
      - op: replace
        path: /spec/path
        value: ./kubernetes/services/baku/dev/seaweedfs/app
    target:
      kind: Kustomization
      name: seaweedfs
