apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name plugin-barman-cloud
  labels:
    app.kubernetes.io/name: *name
    app.kubernetes.io/instance: *name
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: *name
      app.kubernetes.io/instance: *name
  # RollingUpdate strategy is not supported by the operator yet, so it can only use the Recreate strategy.
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: *name
        app.kubernetes.io/instance: *name
    spec:
      containers:
      - args:
        - operator
        - --server-cert=/server/tls.crt
        - --server-key=/server/tls.key
        - --client-cert=/client/tls.crt
        - --server-address=:9090
        - --leader-elect
        - --log-level=debug
        env:
        - name: SIDECAR_IMAGE
          valueFrom:
            configMapKeyRef:
              key: SIDECAR_IMAGE
              name: plugin-barman-cloud-config
        image: "ghcr.io/cloudnative-pg/plugin-barman-cloud:v0.9.0"
        name: barman-cloud
        ports:
        - containerPort: 9090
          protocol: TCP
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 9090
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsUser: 10001
          runAsGroup: 10001
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
              - "ALL"
        volumeMounts:
        - mountPath: /server
          name: server
        - mountPath: /client
          name: client
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: plugin-barman-cloud
      volumes:
      - name: server
        secret:
          secretName: barman-cloud-server-tls
      - name: client
        secret:
          secretName: barman-cloud-client-tls
