# vscode-kubernetes-tools: exclude
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: seaweedfs
resources:
  - ../../../base/seaweedfs/app
patches:
  - path: helm-release-patch.yaml
    target:
      kind: HelmRelease
      name: seaweedfs
      namespace: seaweedfs
