# vscode-kubernetes-tools: exclude
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../common/base/kube-system
  - ../base/traefik
  - ../base/external-secrets
  - cert-manager
  - external-dns
  - ../base/openbao
  - ../base/database
  - ../base/zitadel
