# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.3/ingress.json
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: &name pocket-id
  annotations:
    traefik.ingress.kubernetes.io/service.serversscheme: h2c
  labels:
    app.kubernetes.io/name: *name
    app.kubernetes.io/instance: *name
spec:
  rules:
    - host: &host ${OIDC_ISSUER_HOST}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: *name
                port:
                  number: 80
  tls:
    - hosts:
        - *host
