# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.3/statefulset.json
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: &name pocket-id
  labels:
    app.kubernetes.io/name: *name
    app.kubernetes.io/instance: *name
    reloader.stakater.com/auto: "true"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: *name
      app.kubernetes.io/instance: *name
  serviceName: *name
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: *name
        app.kubernetes.io/instance: *name
    spec:
      serviceAccountName: *name
      containers:
        - name: *name
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          # renovate: datasource=docker image=pocket-id/pocket-id
          image: ghcr.io/pocket-id/pocket-id:v1.16.0-distroless
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 1411
              protocol: TCP
          envFrom:
            - configMapRef:
                name: pocket-id-config
            - secretRef:
                name: *name
          livenessProbe:
            initialDelaySeconds: 10
            htpGet:
              path: /healthz
              port: http
          readinessProbe:
            initialDelaySeconds: 10
            htpGet:
              path: /healthz
              port: http
          # resources:
          #   requests:
          #     memory: 96Mi
          #     cpu: 20m
          #   limits:
          #     memory: 512Mi
          #     cpu: 200m
